# Generated by Django 4.1.7 on 2023-03-30 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testsolving', '0011_alter_useranswer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
