# Generated by Django 4.1.7 on 2023-03-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsolving', '0012_testresult_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.PositiveIntegerField(choices=[(models.CharField(max_length=255), 'Option 1'), (models.CharField(max_length=255), 'Option 2'), (models.CharField(max_length=255), 'Option 3'), (models.CharField(max_length=255), 'Option 4')]),
        ),
    ]
