# Generated by Django 4.1.7 on 2023-03-17 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsolving', '0003_remove_choice_question_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='created_by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='test',
            name='duration',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(max_length=255)),
                ('correct_answer', models.PositiveIntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], default=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testsolving.test')),
            ],
        ),
    ]
