# Generated by Django 4.1.7 on 2023-03-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsolving', '0005_test_questions_alter_question_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='test_questions', to='testsolving.question'),
        ),
    ]
